// This file is generated by scripts/generate-legal-consent.mjs. Do not edit manually.
export const legalConsentVersion = "2026-05-14.beta-direct.v1";
export const legalConsentDocumentHash = "sha256-8b11489a8e5efe16bfc807a7a00caa22aa9ea93a336d8d27fb9c6f693cbb4751";
export const legalConsentDocuments = [
  {
    "id": "installer-terms",
    "path": "docs/legal/INSTALLER_TERMS.md",
    "sha256": "03bd9d0a693d058115681957c6f96c88df16ba12302806fc95256516c5d5c4cc",
    "bytes": 581
  },
  {
    "id": "developer-disclosure",
    "path": "docs/legal/DEVELOPER_DISCLOSURE.md",
    "sha256": "1be4d04645eee9e72fff9e1468cfebd06dc454fc11d43133c96af6b79fb4cf0e",
    "bytes": 768
  },
  {
    "id": "eula",
    "path": "docs/legal/EULA.md",
    "sha256": "1cfe62142d9fc8d306dc2f0103fee7781bf28e9451a5a524eba4aca65e13c5cb",
    "bytes": 762
  },
  {
    "id": "privacy",
    "path": "docs/legal/PRIVACY.md",
    "sha256": "9b3c82be96a67f76176a6834713b44f55d402270d219e569484a42be980653c2",
    "bytes": 728
  },
  {
    "id": "refund-policy",
    "path": "docs/legal/REFUND_POLICY.md",
    "sha256": "1f6e8c3e7fe9c71af53195225236b8baa14d05824bc0d024e2a56065ecb9661c",
    "bytes": 906
  },
  {
    "id": "digital-content-waiver",
    "path": "docs/legal/DIGITAL_CONTENT_WAIVER.md",
    "sha256": "9528bad3221419feb2e4efec437db3ccdef658a935faa94bdaee75c63c6b9b26",
    "bytes": 768
  },
  {
    "id": "ai-agent-risk-notice",
    "path": "docs/legal/AI_AGENT_RISK_NOTICE.md",
    "sha256": "246bb65c20d4c53317aeb244980f34e0bb3d8fc8d8ff232c5f24f5ae85c38cf3",
    "bytes": 721
  },
  {
    "id": "openclaw-mit-notice",
    "path": "docs/legal/OPENCLAW_MIT_NOTICE.md",
    "sha256": "4e8e9f3bd6cb9eeccb40e7086781b46890bddabea1586253f962296af15d5c5e",
    "bytes": 2566
  },
  {
    "id": "openclaw-upstream-license",
    "path": "docs/legal/OPENCLAW_UPSTREAM_LICENSE.md",
    "sha256": "ae63c333da96ec7de79a04955ec47ee7ba0664d34648a82f929f28b10dd180f5",
    "bytes": 1211
  }
] as const;
