// This file is generated by scripts/generate-legal-consent.mjs. Do not edit manually.
export const legalConsentVersion = "2026-05-14.beta-direct.v1";
export const legalConsentDocumentHash = "sha256-03e9010619df07370cbc7bfd2c03b30ec02c61379406a59700cd96f888974a63";
export const legalConsentDocuments = [
  {
    "id": "installer-terms",
    "path": "docs/legal/INSTALLER_TERMS.md",
    "sha256": "12c107dd3a065eafd5824a4d9c13d081c9442913772563f9ec0ead03542b8828",
    "bytes": 5798
  },
  {
    "id": "eula",
    "path": "docs/legal/EULA.md",
    "sha256": "1cfe62142d9fc8d306dc2f0103fee7781bf28e9451a5a524eba4aca65e13c5cb",
    "bytes": 762
  },
  {
    "id": "privacy",
    "path": "docs/legal/PRIVACY.md",
    "sha256": "9b3c82be96a67f76176a6834713b44f55d402270d219e569484a42be980653c2",
    "bytes": 728
  },
  {
    "id": "refund-policy",
    "path": "docs/legal/REFUND_POLICY.md",
    "sha256": "f6bdb8ee4ae896fc953bcb8e567ec92152711599ca13fe81b3c42382abdd6782",
    "bytes": 641
  },
  {
    "id": "digital-content-waiver",
    "path": "docs/legal/DIGITAL_CONTENT_WAIVER.md",
    "sha256": "165516fbdf1eab4141eb4a2f6cfb9c2949f0c83c72c65f1dd4ee02dee8205ad8",
    "bytes": 503
  },
  {
    "id": "ai-agent-risk-notice",
    "path": "docs/legal/AI_AGENT_RISK_NOTICE.md",
    "sha256": "246bb65c20d4c53317aeb244980f34e0bb3d8fc8d8ff232c5f24f5ae85c38cf3",
    "bytes": 721
  },
  {
    "id": "openclaw-mit-notice",
    "path": "docs/legal/OPENCLAW_MIT_NOTICE.md",
    "sha256": "4e8e9f3bd6cb9eeccb40e7086781b46890bddabea1586253f962296af15d5c5e",
    "bytes": 2566
  },
  {
    "id": "openclaw-upstream-license",
    "path": "docs/legal/OPENCLAW_UPSTREAM_LICENSE.md",
    "sha256": "ae63c333da96ec7de79a04955ec47ee7ba0664d34648a82f929f28b10dd180f5",
    "bytes": 1211
  }
] as const;
