export const targetRegistryCopy = {
  targetRegistryTitle: "Target Registry",
  targetRegistrySubtitle: "把 local-shell、SSH 終端機與遠端桌面收斂成同一個安全派發面板。",
  targetRegistryUseHint: "先預覽，再送出紀錄；高風險或未配對狀態會被 contract 擋下。",
  targetRegistryRefresh: "重新讀取",
  targetRegistryNewLocal: "新增本機",
  targetRegistryNewSsh: "新增 SSH",
  targetRegistryNewRemoteDesktop: "新增遠端桌面",
  targetRegistryNewMock: "新增 Mock",
  targetRegistrySummaryTotalPrefix: "總目標數",
  targetRegistrySummaryDefaultPrefix: "預設目標：",
  targetRegistrySummaryReadyPrefix: "就緒",
  targetRegistrySummaryPairedPrefix: "已配對",
  targetRegistrySummaryDispatchLogPrefix: "dispatch log",
  targetRegistrySummaryGroupPrefix: "群組",
  targetRegistrySummaryReadyDescription: "只有就緒且已配對的 target 才會進入安全派發選擇。",
  targetRegistrySummaryDispatchDescription: "先預覽，再送出紀錄；高風險或未配對狀態會被 contract 擋下。",
  targetRegistryDraftTitle: "目標設定",
  targetRegistryDraftTitleNew: "新目標草稿",
  targetRegistryDraftDescription: "這裡定義每台電腦的連線類型、配對狀態與可授權範圍。",
  targetRegistryDispatchTitle: "派發預覽",
  targetRegistryDispatchDescription: "先做本地判斷，再把安全決策送到 gateway 當成 audit record。",
  targetRegistryDraftSaved: "目前狀態：",
  targetRegistryDraftEditing: "編輯中",
  targetRegistryDraftSavedAligned: "已對齊 registry",
  targetRegistryDraftUnsaved: "草稿尚未儲存",
  targetRegistryDraftGroupSavedTitle: "已保存群組",
  targetRegistryDraftGroupSavedHint: "可直接套用到 broadcast selection。",
  targetRegistryDraftGroupSelectionHint: "選取 target 後可儲存成 group / fleet preset。",
  targetRegistryDraftGroupBroadcastHint: "group 會直接驅動多目標 batch execute。",
  targetRegistryDraftGroupDescription: "適合重複派發的 target 組合。",
  targetRegistryDraftGroupInstruction: "先選 target，再儲存成群組或直接套用。",
  targetRegistryDraftGroupEmpty: "尚未建立群組。",
  targetRegistryDraftGroupNoSelection: "未選擇",
  targetRegistryDraftGroupNameRequired: "請先輸入群組名稱。",
  targetRegistryDraftGroupSelectionRequired: "請先選擇至少一個 target。",
  targetRegistryDraftGroupActive: "active",
  targetRegistryDraftGroupDefault: "default",
  targetRegistryDraftGroupSelected: "selected",
  targetRegistryDraftGroupNone: "none",
  targetRegistryDraftGroupReady: "ready",
  targetRegistryDraftGroupNeed: "needs",
  targetRegistryDraftGroupBlock: "blocked",
  targetRegistryDraftGroupBrowse: "群組",
  targetRegistryDraftGroupTargetSuffix: "targets",
  targetRegistryDraftGroupCountSuffix: "groups",
  targetRegistryDraftGroupApplyToSelection: "套用到選擇",
  targetRegistryDraftGroupSaveAs: "保存為群組",
  targetRegistryDraftGroupRemove: "移除群組",
  targetRegistryDraftGroupSavedMessage: (name: string) => `已儲存群組 ${name}。`,
  targetRegistryDraftGroupAppliedMessage: (name: string) => `已套用群組 ${name}。`,
  targetRegistryDraftGroupDeletedMessage: (name: string) => `已刪除群組 ${name}。`,
  targetRegistryRegistryLocalLoadedMessage: "已使用本機預設 target 登錄。",
  targetRegistryRegistryGatewayLoadedMessage: "已讀取 gateway target registry。",
  targetRegistryRegistryGatewayFallbackMessage: "無法讀取 gateway 的 target registry，已切回本機預設清單。",
  targetRegistryReadinessCopiedMessage: (targetName: string) => `已複製 ${targetName} 的 connection readiness report。`,
  targetRegistryReadinessCopyFailedMessage: "無法複製 readiness report。",
  targetRegistryDraftCreatedMessage: (displayName: string) => `已建立 ${displayName} 的草稿。`,
  targetRegistryDraftSavedMessage: (displayName: string) => `已儲存 ${displayName}。`,
  targetRegistryDraftSavedDefaultMessage: (displayName: string) => `已儲存 ${displayName} 並設為預設 target。`,
  targetRegistryDraftSavedLocalFallbackMessage: (statusMessage: string) => `${statusMessage}（僅保留本機狀態，gateway 儲存失敗）`,
  targetRegistryDispatchPreviewCreatedMessage: (displayName: string) => `已產生 ${displayName} 的派發預覽。`,
  targetRegistryDispatchRecordCreatedMessage: (targetName: string) => `已建立 ${targetName} 的派發紀錄。`,
  targetRegistryDispatchRecordCreatedLocalMessage: "已建立本機派發紀錄，但 gateway 儲存失敗。",
  targetRegistryDispatchPreviewLocalError: "派發預覽已在本機產生，但 gateway 回傳失敗。",
  targetRegistryDispatchExecuteSafeOnly: "只有 execute_safe 分類才能直接執行。",
  targetRegistryDispatchGatewayRequired: "需要 gateway 才能執行實際連線。",
  targetRegistryDispatchExecutionFailed: "安全命令執行失敗，請先確認 ssh / PowerShell 可用且 target 已正確配對。",
  targetRegistryCredentialRefGatewayRequired: "需要 gateway 才能發行 credential ref。",
  targetRegistryCredentialRefOnlyRemote: "只有 SSH / 遠端桌面 target 才能發行 credential ref。",
  targetRegistryCredentialSecretSshRequired: "請先貼上 SSH private key。",
  targetRegistryCredentialSecretRdpRequired: "請先貼上遠端桌面登入 secret / password。",
  targetRegistryCredentialBundleGatewayRequiredExport: "需要 gateway 才能匯出 credential bundle。",
  targetRegistryCredentialBundleGatewayRequiredPreview: "需要 gateway 才能預覽 credential bundle。",
  targetRegistryCredentialBundleGatewayRequiredImport: "需要 gateway 才能匯入 credential bundle。",
  targetRegistryCredentialBundlePassphraseRequired: "請先輸入 bundle passphrase。",
  targetRegistryCredentialBundleJsonRequired: "請先貼上 credential bundle JSON。",
  targetRegistrySSHSessionBlocked: "只有 SSH target 才能操作 session。",
  targetRegistrySSHSessionSaveRequired: "請先儲存這個 target，再與 gateway 互動。",
  targetRegistrySSHCommandRequired: "請先輸入 SSH command。",
  targetRegistrySSHSessionOpenRequired: "請先開啟 SSH terminal session。",
  targetRegistrySSHSessionOpenMessage: "已在本機預覽中開啟 SSH session。",
  targetRegistrySSHSessionCloseMessage: "已在本機預覽中關閉 SSH session。",
  targetRegistrySSHSessionRefreshMessage: "已在本機預覽中重新整理 SSH session。",
  targetRegistryHostKeyVerified: "verified",
  targetRegistryHostKeyNotVerified: "not verified",
  targetRegistryTargetListTrustedWorkspaceCount: "目前解析出 {count} 個 trusted workspace。",
  fieldSshPrivateKeyPlaceholder: "-----BEGIN OPENSSH PRIVATE KEY-----",
  fieldRemoteDesktopSecretPlaceholder: "RDP password / secret token",
  fieldCredentialRefGatewayOnly: "只會發行成 gateway-managed credential ref，不會寫入 repo 或 debug bundle。",
  fieldKnownHostKeyHint: "驗證時會寫入 gateway 管理的 known_hosts，不會顯示實際路徑。",
  fieldKnownHostKeyPlaceholder: "ssh-ed25519 AAAA...",
  fieldConnectionNotePlaceholder: "例如：僅允許登入後執行 git status / collect-debug-bundle",
  fieldProbeNotYet: "未探測",
  fieldProbeLatencyNa: "n/a",
  fieldProbeErrorNone: "none",
  targetRegistryRemoteDesktopBlocked: "只有遠端桌面 target 才能操作 session。",
  targetRegistryRemoteDesktopSaveRequired: "請先儲存遠端桌面 target，再與 gateway 互動。",
  targetRegistryRemoteDesktopGatewayRequired: "需要 gateway 才能請求遠端桌面控制。",
  targetRegistryConnectionReadinessReady: "所有必要條件都已滿足，可以進入 connect。",
  targetRegistryConnectionReadinessNextStepPrefix: "下一步建議：",
  targetRegistryConnectionReadinessSourcePrefix: "source：",
  targetRegistryConnectionReadinessReadyToConnectPrefix: "ready to connect：",
  targetRegistryConnectionReadinessNextActionPrefix: "next action：",
  targetRegistryConnectionReadinessLastProbePrefix: "last probe：",
  targetRegistryConnectionReadinessExecuteAction: "執行建議動作",
  targetRegistryConnectionReadinessCopyAction: "複製 readiness report",
  targetRegistryConnectionReadinessRefreshAction: "重新整理 readiness",
  targetRegistryConnectionReadinessTitle: "Connection readiness",
  targetRegistryConnectionReadinessStatusPrefix: "status",
  targetRegistryConnectionReadinessRequired: "required",
  targetRegistryConnectionReadinessOptional: "optional",
  targetRegistryTargetListReadinessPrefix: "readiness：",
  targetRegistryTargetListBroadcast: "broadcast",
  targetRegistryTargetListReadinessReady: "ready",
  targetRegistryTargetListReadinessNeed: "needs",
  targetRegistryTargetListReadinessProbe: "probe",
  targetRegistryTargetListReadinessActive: "active",
  targetRegistryTargetListReadinessCopy: "複製 readiness report",
  targetRegistryTargetListReadinessAction: "執行建議動作",
  targetRegistryTargetListReadinessRefresh: "重新整理 readiness",
  targetRegistryTargetListTimelineTitle: "target timeline",
  targetRegistryTargetListTimelineGlobalTitle: "global dispatch log",
  targetRegistryTargetListTimelineEmpty: "尚未有派發紀錄。",
  targetRegistryTargetListTimelineNoSelection: "尚未選取 target。",
  targetRegistryTargetListTimelineNoRecords: "尚未有這台 target 的派發紀錄。",
  targetRegistryTargetListTimelineSource: "source",
  targetRegistryTargetListTimelineReadyToConnect: "ready to connect",
  targetRegistryTargetListTimelineNextAction: "next action",
  targetRegistryTargetListTimelineLastProbe: "last probe",
  targetRegistryTargetListTimelineBatchExecution: "Batch execution",
  targetRegistryTargetListTimelineLatestPreview: "最新預覽",
  targetRegistryTargetListTimelineLatestExecution: "最近執行結果",
  targetRegistryTargetListAuditReportTitle: "target audit report",
  targetRegistryTargetListAuditReportCopy: "複製 audit report",
  targetRegistryTargetListAuditReportRefresh: "重新整理 audit report",
  targetRegistryTargetListAuditReportDownload: "下載 audit report",
  targetRegistryTargetListAuditReportHint: "匯出可分享的 target / timeline / readiness 稽核摘要，不包含明文 secret。",
  targetRegistryTargetListAuditReportNoSelection: "尚未選取 target。",
  targetRegistryTargetListAuditReportNoRecords: "尚未有可匯出的 audit report。",
  targetRegistryTargetListAuditReportCopied: "已複製 audit report。",
  targetRegistryTargetListAuditReportDownloaded: "已下載 audit report。",
  targetRegistryTargetListAuditReportCopyFailed: "無法複製 audit report。",
  targetRegistryTargetListSessionExportDownloaded: "已下載 session export。",
  targetRegistryTargetListSessionExportFailed: "無法下載 session export。",
  targetRegistryTargetListTimelineGroupCount: "{count} groups",
  targetRegistryTargetListTimelineGroupLabel: "Target groups",
  targetRegistryTargetListTimelineGroupPreset: "群組",
  targetRegistryTargetListTimelineGroupApply: "套用群組",
  targetRegistryTargetListTimelineGroupSave: "儲存為群組",
  targetRegistryTargetListTimelineGroupDelete: "刪除群組",
  targetRegistryTargetListTimelineGroupName: "群組名稱",
  targetRegistryTargetListTimelineGroupDescription: "群組描述",
  targetRegistryTargetListTimelineGroupSelect: "未選擇",
  targetRegistryTargetListTimelineGroupSelected: "selected",
  targetRegistryTargetListTimelineGroupTargets: "{count} targets",
  targetRegistryTargetListTimelineBundleTitle: "Credential Bundle",
  targetRegistryTargetListTimelineBundleExport: "匯出目標",
  targetRegistryTargetListTimelineBundlePreview: "Bundle preview",
  targetRegistryTargetListTimelineBundlePassphrase: "Bundle passphrase",
  targetRegistryTargetListTimelineBundleImport: "Import bundle JSON",
  targetRegistryTargetListTimelineBundleHint: "使用 passphrase 將目前 target registry 與已發行的 credential refs 匯出成加密 bundle，方便換機或跨機器部署。",
  targetRegistryTargetListTimelineBundleExportHint: "匯出時只包含勾選的 target；未勾選者不會進 bundle。",
  targetRegistryTargetListTimelineBundleImportHint: "bundle 內只保存加密後的 credential payload；匯入時會重新發行 gateway-managed credential refs。",
  targetRegistryTargetListTimelineBundleTargetIds: "targetIds",
  targetRegistryTargetListTimelineBundleTargetNames: "targetNames",
  targetRegistryTargetListTimelineBundleGroupIds: "groupIds",
  targetRegistryTargetListTimelineBundleGroupNames: "groupNames",
  targetRegistryTargetListTimelineBundleSecretKinds: "secretKinds",
  targetRegistryTargetListTimelineBundleSecretLabels: "secretLabels",
  targetRegistryTargetListTimelineBundleAddedTargets: "新增 target",
  targetRegistryTargetListTimelineBundleUpdatedTargets: "更新 target",
  targetRegistryTargetListTimelineBundleUnchangedTargets: "不變 target",
  targetRegistryTargetListTimelineBundleAddedGroups: "新增 group",
  targetRegistryTargetListTimelineBundleUpdatedGroups: "更新 group",
  targetRegistryTargetListTimelineBundleUnchangedGroups: "不變 group",
  targetRegistryTargetListTimelineBundleSecretTargets: "secret targets",
  targetRegistryTargetListTimelineBundleOverwriteCount: "overwrite count",
  targetRegistryTargetListTimelineBundleGroupOverwriteCount: "group overwrite count",
  title: "Target Registry",
  subtitle: "把 local-shell、SSH 終端機與遠端桌面收斂成同一個安全派發面板。",
  refresh: "重新讀取",
  summaryReady: "就緒",
  summaryPaired: "已配對",
  summaryDispatchLog: "dispatch log",
  summaryDefaultTarget: "預設目標：{value}",
  summaryReadyDescription: "只有就緒且已配對的 target 才會進入安全派發選擇。",
  summaryDispatchDescription: "先預覽，再送出紀錄；高風險或未配對狀態會被 contract 擋下。",
  targetGroupsTitle: "Target groups",
  targetGroupsCount: "{count} groups",
  targetGroupsSelectLabel: "套用群組",
  targetGroupsNameLabel: "群組名稱",
  targetGroupsDescriptionLabel: "群組描述",
  targetGroupsNamePlaceholder: "例如：每天早上巡檢",
  targetGroupsDescriptionPlaceholder: "選填，說明這組 target 的用途",
  targetGroupsSave: "儲存為群組",
  targetGroupsApply: "套用群組",
  targetGroupsDelete: "刪除群組",
  targetGroupsEmpty: "未選擇",
  targetGroupsChipTargets: "{count} targets",
  targetGroupsSelectedBroadcast: "broadcast",
  targetGroupsDefault: "Local + SSH",
  targetGroupsDefaultDescription: "本機與 SSH 終端機的日常發配群組。",
  targetGroupsRemoteOps: "Remote Ops",
  targetGroupsRemoteOpsDescription: "遠端桌面與 lab target 的觀察 / 控制群組。",
  targetGroupsAll: "All Targets",
  targetGroupsAllDescription: "全部已註冊 target。",
  targetGroupsTargetListHeader: "Target groups",
  targetGroupsTargetListHint: "{count} targets",
  targetGroupsPresetApply: "套用群組",
  targetGroupsPresetDelete: "刪除群組",
  targetGroupsPresetSave: "儲存為群組",
  targetGroupsPresetCount: "{count} groups",
  targetGroupsPresetName: "群組名稱",
  targetGroupsPresetDescription: "群組描述",
  targetGroupsPresetSelect: "未選擇",
  targetGroupsPresetHint: "選擇或建立可重複使用的 fleet preset。",
  targetGroupsPresetSummary: "選取的 target 會被保存為可重複使用的群組。",
  targetGroupsPresetSelectButton: "套用群組",
  targetGroupsPresetSaveButton: "儲存為群組",
  targetGroupsPresetDeleteButton: "刪除群組",
  targetGroupsPresetNoSelection: "請先選擇至少一個 target。",
  targetGroupsPresetNameRequired: "請先輸入群組名稱。",
  targetGroupsPresetSaved: "已儲存群組 {name}。",
  targetGroupsPresetApplied: "已套用群組 {name}。",
  targetGroupsPresetDeleted: "已刪除群組 {name}。",
  targetGroupsPresetList: "{count} targets",
  targetGroupsPresetActive: "active",
  targetGroupsPresetDefault: "default",
  targetGroupsPresetBrowse: "群組",
  targetGroupsPresetSavedTitle: "已保存群組",
  targetGroupsPresetSavedHint: "可直接套用到 broadcast selection。",
  targetGroupsPresetSelectionHint: "選取 target 後可儲存成 group / fleet preset。",
  targetGroupsPresetBroadcastHint: "group 會直接驅動多目標 batch execute。",
  targetGroupsPresetInstruction: "先選 target，再儲存成群組或直接套用。",
  targetGroupsPresetEmpty: "尚未建立群組。",
  targetGroupsPresetApplyToSelection: "套用到選擇",
  targetGroupsPresetSaveAs: "保存為群組",
  targetGroupsPresetRemove: "移除群組",
  targetGroupsPresetCountSuffix: "groups",
  targetGroupsPresetTargetSuffix: "targets",
  targetGroupsPresetSelected: "selected",
  targetGroupsPresetNone: "none",
  targetGroupsPresetReady: "ready",
  targetGroupsPresetNeed: "needs",
  targetGroupsPresetBlock: "blocked",
  draftTitle: "目標設定",
  draftTitleNew: "新目標草稿",
  draftDescription: "這裡定義每台電腦的連線類型、配對狀態與可授權範圍。",
  fieldTargetId: "Target ID",
  fieldDisplayName: "顯示名稱",
  fieldKind: "類型",
  fieldEndpoint: "Endpoint",
  fieldState: "連線狀態",
  fieldPaired: "已配對",
  fieldAuthenticated: "已驗證認證",
  fieldHostKey: "SSH host key verified",
  fieldTrustedWorkspaces: "Trusted workspaces",
  fieldConnectionUsername: "Connection username",
  fieldConnectionPort: "Connection port",
  fieldCredentialMode: "Credential mode",
  fieldCredentialRef: "Credential ref",
  fieldSshPrivateKey: "SSH private key",
  fieldRemoteDesktopSecret: "Remote desktop credential secret",
  fieldKnownHostKey: "SSH known host key",
  fieldSessionMode: "Session mode",
  fieldConnectionNote: "Connection note",
  fieldConnectionStatus: "配對狀態",
  fieldAuthenticationStatus: "認證",
  fieldLastSeen: "Last seen",
  fieldConnectionProfile: "Connection profile",
  fieldProbe: "Probe",
  fieldProbeEndpoint: "Probe endpoint",
  fieldProbeAt: "Probe at",
  fieldProbeLatency: "Probe latency",
  fieldProbeError: "Probe error",
  fieldConnectionReadiness: "Connection readiness",
  fieldConnectionReadyToConnect: "ready to connect",
  fieldConnectionNextAction: "next action",
  fieldConnectionLastProbe: "last probe",
  fieldConnectionSource: "source",
  fieldBundleTitle: "Credential Bundle",
  fieldBundleSubtitle: "加密匯出 / 匯入",
  fieldBundleDescription: "使用 passphrase 將目前 target registry 與已發行的 credential refs 匯出成加密 bundle，方便換機或跨機器部署。",
  fieldBundleExportTargets: "匯出目標",
  fieldBundlePassphrase: "Bundle passphrase",
  fieldBundleImportJson: "Import bundle JSON",
  fieldBundlePreviewTitle: "Bundle preview",
  fieldBundlePreviewTargetIds: "targetIds",
  fieldBundlePreviewTargetNames: "targetNames",
  fieldBundlePreviewGroupIds: "groupIds",
  fieldBundlePreviewGroupNames: "groupNames",
  fieldBundlePreviewSecretKinds: "secretKinds",
  fieldBundlePreviewSecretLabels: "secretLabels",
  fieldBundlePreviewAddedTargets: "新增 target",
  fieldBundlePreviewUpdatedTargets: "更新 target",
  fieldBundlePreviewUnchangedTargets: "不變 target",
  fieldBundlePreviewAddedGroups: "新增 group",
  fieldBundlePreviewUpdatedGroups: "更新 group",
  fieldBundlePreviewUnchangedGroups: "不變 group",
  fieldBundlePreviewSecretTargets: "secret targets",
  fieldBundlePreviewOverwriteCount: "overwrite count",
  fieldBundlePreviewGroupOverwriteCount: "group overwrite count",
  fieldTimelineTarget: "target timeline",
  fieldTimelineGlobal: "global dispatch log",
  fieldTimelineEmpty: "尚未有這台 target 的派發紀錄。",
  fieldTimelineEmptyGlobal: "尚未有派發紀錄。",
  fieldTimelineNoSelection: "尚未選取 target。",
  fieldDispatchPreview: "派發預覽",
  fieldDispatchSummary: "摘要",
  fieldDispatchCommand: "命令 / 動作",
  fieldDispatchLatestPreview: "最新預覽",
  fieldDispatchLatestExecution: "最近執行結果",
  fieldDispatchBatchExecution: "Batch execution",
  fieldDispatchBroadcast: "broadcast",
  fieldDispatchMode: "分類",
  fieldDispatchExecutionButton: "審批並執行",
  fieldDispatchBatchButton: "批次執行",
  fieldDispatchCreateRecord: "建立紀錄",
  fieldDispatchLocalPreview: "本機預覽模式：未執行實際 SSH 命令。",
  fieldDispatchReadyPrompt: "尚未產生預覽，請先按「預覽」。",
  fieldDispatchTarget: "目標",
  fieldDispatchSecurity: "安全狀態",
  fieldDispatchSafetyWaiting: "等待預覽",
  fieldDispatchTrustedWorkspaces: "trusted workspaces",
  fieldDispatchSummaryHint: "說明這次要做什麼",
  fieldDispatchCommandHint: "例如 git status / collect-debug-bundle / request-human-approval",
  fieldDispatchPreviewTitle: "最新預覽",
  fieldDispatchPreviewAdapter: "adapter",
  fieldDispatchPreviewUnsafe: "安全命令執行失敗，請先確認 ssh / PowerShell 可用且 target 已正確配對。",
  fieldCredentialBundlePreview: "credential bundle preview",
  fieldCredentialBundleSummary: "加密匯出 / 匯入",
  fieldCredentialBundleHint: "bundle 內只保存加密後的 credential payload；匯入時會重新發行 gateway-managed credential refs。",
  fieldCredentialBundleExportHint: "匯出時只包含勾選的 target；未勾選者不會進 bundle。",
  fieldCredentialBundleImportRequired: "請先貼上 credential bundle JSON。",
  fieldCredentialBundlePassphraseRequired: "請先輸入 bundle passphrase。",
  fieldCredentialBundleGatewayRequiredExport: "需要 gateway 才能匯出 credential bundle。",
  fieldCredentialBundleGatewayRequiredPreview: "需要 gateway 才能預覽 credential bundle。",
  fieldCredentialBundleGatewayRequiredImport: "需要 gateway 才能匯入 credential bundle。",
  fieldCredentialRefGatewayRequired: "需要 gateway 才能發行 credential ref。",
  fieldCredentialRefOnlyRemote: "只有 SSH / 遠端桌面 target 才能發行 credential ref。",
  fieldSSHSessionTitle: "SSH Terminal Session",
  fieldSSHSessionReady: "SSH session 已開啟，可送出 allowlisted command。",
  fieldSSHSessionClosed: "SSH session 已關閉，必要時可重新開啟。",
  fieldSSHSessionPrompt: "尚未開啟 SSH session，請先按開啟 Session。",
  fieldSSHCommandLabel: "SSH command",
  fieldSSHSessionHint: "只會透過 safe-dispatch 與 gateway-managed SSH session contract 執行 allowlisted 命令。",
  fieldSSHSessionNoTranscript: "尚未建立 transcript。",
  fieldSSHSessionBlocked: "只有 SSH target 才能操作 session。",
  fieldSSHSessionSaveRequired: "請先儲存這個 target，再與 gateway 互動。",
  fieldSSHCommandRequired: "請先輸入 SSH command。",
  fieldSSHSessionOpenRequired: "請先開啟 SSH terminal session。",
  fieldSSHSessionOpenMessage: "已在本機預覽中開啟 SSH session。",
  fieldSSHSessionCloseMessage: "已在本機預覽中關閉 SSH session。",
  fieldSSHSessionRefreshMessage: "已在本機預覽中重新整理 SSH session。",
  fieldRemoteDesktopTitle: "遠端桌面 Session",
  fieldRemoteDesktopSummaryTitle: "遠端桌面 Session",
  fieldRemoteDesktopBlocked: "只有遠端桌面 target 才能操作 session。",
  fieldRemoteDesktopSaveRequired: "請先儲存遠端桌面 target，再與 gateway 互動。",
  fieldRemoteDesktopGatewayRequired: "需要 gateway 才能請求遠端桌面控制。",
  fieldRemoteDesktopCredentialKind: "RDP credential ref",
  fieldRemoteDesktopCredentialLabel: "Remote desktop credential secret",
  fieldRemoteDesktopLaunchButton: "啟動 RDP Client",
  fieldRemoteDesktopReconnectButton: "重新連線",
  fieldRemoteDesktopSeedButton: "準備登入憑證",
  fieldRemoteDesktopObserveButton: "觀察",
  fieldRemoteDesktopRequestControlButton: "請求控制",
  fieldRemoteDesktopReleaseButton: "釋放控制",
  fieldRemoteDesktopDisconnectButton: "中止並斷線",
  fieldRemoteDesktopRefreshButton: "重新整理",
  fieldRemoteDesktopLaunchState: "launch",
  fieldRemoteDesktopLaunchHistory: "launch history",
  fieldSessionExportButton: "下載 session export",
  fieldSSHTranscriptExportTitle: "SSH session export",
  fieldRemoteDesktopSessionExportTitle: "遠端桌面 session export",
  fieldSessionExportHint: "下載目前 session 的 Markdown 匯出，不包含明文 secret。",
  fieldRemoteDesktopSessionSummary: "summary",
  fieldRemoteDesktopCredentialSource: "credential source",
  fieldRemoteDesktopCredentialSeedState: "credential seed state",
  fieldRemoteDesktopClientLaunchState: "client launch state",
  fieldRemoteDesktopClientLaunchCommand: "client launch command",
  fieldRemoteDesktopClientLaunchPid: "client launch pid",
  fieldRemoteDesktopClientLaunchError: "client launch error",
  fieldRemoteDesktopVisibleWindows: "visible windows",
  fieldRemoteDesktopActiveWindow: "active window",
  fieldRemoteDesktopScreenSummary: "screen summary",
  fieldRemoteDesktopPermissionRequest: "permission request",
  fieldRemoteDesktopControlMode: "control",
  fieldRemoteDesktopObserveMode: "observe",
  fieldRemoteDesktopLaunchDryRun: "dry-run",
  fieldRemoteDesktopLaunchLaunched: "launched",
  fieldRemoteDesktopLaunchFailed: "failed",
  fieldRemoteDesktopLaunchIdle: "idle",
  fieldRemoteDesktopSessionIdle: "idle",
  fieldRemoteDesktopSessionObserving: "observing",
  fieldRemoteDesktopSessionControlPending: "control-pending",
  fieldRemoteDesktopSessionControlling: "controlling",
  fieldRemoteDesktopSessionReleased: "released",
  fieldRemoteDesktopLaunchHint: "Native remote desktop client launch helper is gated.",
  fieldConnectionBadgeReady: "ready",
  fieldConnectionBadgeNeedPair: "pair",
  fieldConnectionBadgeNeedProbe: "probe",
  fieldConnectionBadgeNeedVerify: "verify_host_key",
  fieldConnectionBadgeNeedConnect: "connect",
  fieldConnectionBadgeNeedRefresh: "refresh",
  fieldConnectionBadgeNeedNone: "none",
  fieldTargetDefaultMark: "預設",
  fieldTargetEndpointMissing: "未設定 endpoint",
  fieldTargetListBroadcast: "broadcast",
  fieldTargetListReadiness: "readiness：",
  fieldTargetListProbe: "probe",
  fieldTargetListReady: "ready",
  fieldTargetListActive: "active",
  fieldTargetListNeed: "needs",
  fieldTargetListConnectionProfile: "Connection profile",
  fieldTargetListConnectionReadiness: "Connection readiness",
  fieldTargetListTargetTimeline: "target timeline",
  fieldTargetListGlobalDispatchLog: "global dispatch log",
  fieldTargetListTimelineEmpty: "尚未有派發紀錄。",
  fieldTargetListTimelineNoSelection: "尚未選取 target。",
  fieldTargetListTimelineNoRecords: "尚未有這台 target 的派發紀錄。",
  fieldTargetListTimelineCopy: "複製 readiness report",
  fieldTargetListTimelineAction: "執行建議動作",
  fieldTargetListTimelineRefresh: "重新整理 readiness",
  fieldTargetListTimelineSource: "source",
  fieldTargetListTimelineReady: "ready to connect",
  fieldTargetListTimelineNextAction: "next action",
  fieldTargetListTimelineLastProbe: "last probe",
  fieldTargetListTimelineBatchResult: "Batch execution",
  fieldTargetListTimelineLatestPreview: "最新預覽",
  fieldTargetListTimelineLatestExecution: "最近執行結果",
  fieldTargetListTimelineReadiness: "Connection readiness",
  fieldTargetListTimelineGroupCount: "{count} groups",
  fieldTargetListTimelineGroupLabel: "Target groups",
  fieldTargetListTimelineGroupPreset: "群組",
  fieldTargetListTimelineGroupApply: "套用群組",
  fieldTargetListTimelineGroupSave: "儲存為群組",
  fieldTargetListTimelineGroupDelete: "刪除群組",
  fieldTargetListTimelineGroupName: "群組名稱",
  fieldTargetListTimelineGroupDescription: "群組描述",
  fieldTargetListTimelineGroupSelect: "未選擇",
  fieldTargetListTimelineGroupSelected: "selected",
  fieldTargetListTimelineGroupTargets: "{count} targets",
  fieldTargetListTimelineBundleTitle: "Credential Bundle",
  fieldTargetListTimelineBundleExport: "匯出目標",
  fieldTargetListTimelineBundlePreview: "Bundle preview",
  fieldTargetListTimelineBundlePassphrase: "Bundle passphrase",
  fieldTargetListTimelineBundleImport: "Import bundle JSON",
  fieldTargetListTimelineBundleHint: "使用 passphrase 將目前 target registry 與已發行的 credential refs 匯出成加密 bundle，方便換機或跨機器部署。",
  fieldTargetListTimelineBundleExportHint: "匯出時只包含勾選的 target；未勾選者不會進 bundle。",
  fieldTargetListTimelineBundleImportHint: "bundle 內只保存加密後的 credential payload；匯入時會重新發行 gateway-managed credential refs。",
  fieldTargetListTimelineBundleTargetIds: "targetIds",
  fieldTargetListTimelineBundleTargetNames: "targetNames",
  fieldTargetListTimelineBundleGroupIds: "groupIds",
  fieldTargetListTimelineBundleGroupNames: "groupNames",
  fieldTargetListTimelineBundleSecretKinds: "secretKinds",
  fieldTargetListTimelineBundleSecretLabels: "secretLabels",
  fieldTargetListTimelineBundleAddedTargets: "新增 target",
  fieldTargetListTimelineBundleUpdatedTargets: "更新 target",
  fieldTargetListTimelineBundleUnchangedTargets: "不變 target",
  fieldTargetListTimelineBundleAddedGroups: "新增 group",
  fieldTargetListTimelineBundleUpdatedGroups: "更新 group",
  fieldTargetListTimelineBundleUnchangedGroups: "不變 group",
  fieldTargetListTimelineBundleSecretTargets: "secret targets",
  fieldTargetListTimelineBundleOverwriteCount: "overwrite count",
  fieldTargetListTimelineBundleGroupOverwriteCount: "group overwrite count",
  targetRegistryFieldYes: "yes",
  targetRegistryFieldNo: "no",
  targetRegistryFieldNone: "none",
  targetRegistryFieldNa: "n/a",
  targetRegistryFieldNotSelected: "未選擇",
  targetRegistryFieldNotConfigured: "未設定",
  targetRegistryFieldNotDetected: "未探測",
  targetRegistryFieldNotEstablished: "未建立",
  targetRegistryFieldNotSet: "未設定 endpoint",
  targetRegistryFieldPaired: "paired",
  targetRegistryFieldNotPaired: "not paired",
  targetRegistryFieldAuthenticated: "authenticated",
  targetRegistryFieldNotAuthenticated: "not authenticated",
  targetRegistryFieldVerified: "verified",
  targetRegistryFieldNotVerified: "not verified",
  targetRegistryFieldCreatedAtPrefix: "createdAt：",
  targetRegistryFieldVersionPrefix: "version：",
  targetRegistryFieldTargetIdsPrefix: "targetIds：",
  targetRegistryFieldTargetNamesPrefix: "targetNames：",
  targetRegistryFieldGroupIdsPrefix: "groupIds：",
  targetRegistryFieldGroupNamesPrefix: "groupNames：",
  targetRegistryFieldSecretKindsPrefix: "secretKinds：",
  targetRegistryFieldSecretLabelsPrefix: "secretLabels：",
  targetRegistryFieldSecretTargetsPrefix: "secret targets：",
  targetRegistryFieldCredentialSourcePrefix: "credential source：",
  targetRegistryFieldCredentialSeedPrefix: "credential seed：",
  targetRegistryFieldLaunchStatePrefix: "launch：",
  targetRegistryFieldLaunchCommandPrefix: "launch command：",
  targetRegistryFieldLaunchPidPrefix: "launch pid：",
  targetRegistryFieldTranscriptEmpty: "尚未建立 transcript。",
  targetRegistryFieldBatchExecutionTitle: "Batch execution",
  targetRegistryFieldDispatchLogTitle: "dispatch log",
  targetRegistryFieldNoDispatchRecords: "尚未有派發紀錄。",
  targetRegistryFieldNoTargetSelected: "尚未選取 target。",
  targetRegistryFieldNoTargetRecords: "尚未有這台 target 的派發紀錄。",
  targetRegistryFieldTargetTimelineTitle: "target timeline",
  targetRegistryFieldGlobalDispatchLogTitle: "global dispatch log",
  targetRegistryFieldAuditReportTitle: "target audit report",
  targetRegistryFieldSSHSessionTitle: "SSH Terminal Session",
  targetRegistryFieldRemoteDesktopSessionTitle: "遠端桌面 Session",
  targetRegistryFieldBundleTitle: "Credential Bundle",
  targetRegistryFieldBundlePreviewTitle: "Bundle preview",
  targetRegistryFieldProbeTitle: "Probe",
  targetRegistryFieldConnectionReadinessTitle: "Connection readiness",
  targetRegistryFieldEnabled: "allow",
  targetRegistryFieldDisabled: "block",
  targetRegistryFieldOverwriteCount: "overwrite count",
  targetRegistryFieldGroupOverwriteCount: "group overwrite count",
  targetRegistryFieldAuditReportCopyButton: "複製 audit report",
  targetRegistryFieldAuditReportRefreshButton: "重新整理 audit report",
  targetRegistryFieldAuditReportDownloadButton: "下載 audit report",
  targetRegistryFieldAuditReportHint: "匯出可分享的 target / timeline / readiness 稽核摘要，不包含明文 secret。",
  fieldCredentialBundlePassphrasePlaceholder: "請輸入僅你知道的匯出密碼",
  fieldCredentialBundleImportPlaceholder: "貼上 export 回傳的 JSON bundleText，例如 {\"version\":1,...}",
  fieldConnectionPortSshPlaceholder: "22",
  fieldConnectionPortRdpPlaceholder: "3389",
  fieldConnectionPortOptionalPlaceholder: "可留空",
  fieldConnectionUsernamePlaceholder: "SSH / RDP 登入帳號",
  fieldCredentialRefPlaceholder: "例如 ssh-builder-secret",
  fieldTrustedWorkspacesPlaceholder: "每行一個工作區，或用逗號分隔",
  fieldSSHCommandPlaceholder: "git status",
  fieldTargetType: "類型",
  fieldCredentialModeNone: "none",
  fieldCredentialModeSecretRef: "secret-ref",
  fieldCredentialModeSshAgent: "ssh-agent",
  fieldCredentialModePlatformManaged: "platform-managed",
  fieldSessionModeObserve: "observe",
  fieldSessionModeControl: "control",
  fieldMcpEmptyPreview: "尚未產生預覽，請先按「預覽」。",
  fieldTargetLabel: "目標",
  fieldSecurityStatusLabel: "安全狀態",
  targetRegistryDraftSaveButton: "儲存目標",
  targetRegistryDraftSaveDefaultButton: "儲存並設為預設",
  fieldSSHSessionOpenButton: "開啟 Session",
  fieldSSHCommandSendButton: "送出命令",
  fieldSSHSessionCloseButton: "關閉 Session",
  fieldSSHCredentialRefIssueButton: "發行 SSH credential ref",
  fieldRemoteDesktopCredentialRefIssueButton: "發行 RDP credential ref",
  fieldBundleExportButton: "匯出 Credential Bundle",
  fieldBundlePreviewButton: "預覽 Credential Bundle",
  fieldBundleImportButton: "匯入 Credential Bundle",
  fieldConnectionBadgeNeedDisconnect: "Disconnect",
  fieldSSHTranscriptTitle: "Transcript",
  fieldSSHSessionStateConnected: "SSH session 已開啟，可送出 allowlisted command。",
  fieldSSHSessionStateClosed: "SSH session 已關閉，必要時可重新開啟。",
  fieldSSHSessionStateIdle: "尚未開啟 SSH session，請先按開啟 Session。",
  fieldRemoteDesktopConnectionHint: "尚未讀取遠端桌面 session，請先按觀察或重新整理。",
  fieldRemoteDesktopSessionStateObserving: "observing",
  fieldRemoteDesktopSessionStateControlPending: "control-pending",
  fieldRemoteDesktopSessionStateControlling: "controlling",
  fieldRemoteDesktopSessionStateReleased: "released",
  fieldRemoteDesktopSessionStateIdle: "idle",
  fieldRemoteDesktopLaunchStateIdle: "idle",
  fieldRemoteDesktopLaunchStateDryRun: "dry-run",
  fieldRemoteDesktopLaunchStateLaunched: "launched",
  fieldRemoteDesktopLaunchStateFailed: "failed",
  fieldSshSessionStateConnected: "已連線",
  fieldSshSessionStateClosed: "已關閉",
  fieldSshSessionStateIdle: "待開啟",
  fieldSshSessionLastCommandPrefix: "last ",
  fieldSshSessionLastNone: "last none",
  fieldSshSessionExitPrefix: "exit ",
  fieldSshSessionExitNa: "exit n/a",
  fieldSshSessionPromptPrefix: "ssh",
} as const;

export function formatTargetRegistryCopy(template: string, value: string): string {
  return template.replace("{value}", value);
}

export function formatTargetRegistryCountCopy(template: string, count: number): string {
  return template.replace("{count}", String(count));
}
